# docker-compose.yml
version: '3'
services:
  server:
    depends_on: 
      - database
    build: ./server
    image: ia5_backend
    ports:
      - 8080:8080
  database:
    build:
      context: ./db
    image: ia5_db
    ports:
      - 5432:5432
    env_file:
      - ./db/database.env # configure postgres
    volumes:
      - data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
volumes:
  data: # named volumes can be managed easier using docker-compose